name: RioWebCMS

on:
  push:
    branches: [ "main" ]

jobs:
  RioWebCMS-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  
      

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        script: | 
          cd /home/u998555632/domains/mediumpurple-peafowl-590205.hostingersite.com/public_html
          git pull origin main
          composer2 update
          composer2 install --no-dev --optimize-autoloader
          chmod -R 775 storage bootstrap/cache
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

