name: RioWebCMS

on:
  push:
    branches: [ "main" ]

jobs:
  RioWebCMS-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  
      

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        script: whoami
