name: RioWebCMS

on:
  push:
    branches: [ "main" ]

jobs:
  RioWebCMS-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Deploy to Server
      run: |
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /home/u998555632/domains/mediumpurple-peafowl-590205.hostingersite.com/public_html
        git pull origin main
        composer2 install --no-dev --optimize-autoloader
        php artisan key:generate
        chmod -R 775 storage bootstrap/cache
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        EOF

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate --force
        php artisan test
 
